[package]
name = "y-server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "*"
actix-web = "*"
serde = { version = "*", features = ["derive"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "postgres" ] }
tokio = "*"
dotenvy = "*"
